ALTER TABLE category
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE category
ALTER COLUMN id SET DATA TYPE UUID USING id::UUID;

ALTER TABLE category
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE category
ALTER COLUMN category_name SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_category_name ON category (category_name);